version: 0.2

env:
  variables:
    nodeversion: 18
    pythonversion: 3.10

phases:
  install:
    runtime-versions:
      python: $pythonversion
      nodejs: $nodeversion

  build:
    commands:
      - bash scripts/deploy.sh

artifacts:
  files:
    - '**/*'
  exclude:
    - 'cdk.out/'
    - 'node_modules/'
    - '**/*/cdk.out/'
    - '**/*/node_modules/'