version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.10
  pre_build:
    commands:
      - echo Cleaning cache...
      - yarn cache clean
      - echo Installing dependencies...
      - yarn install --check-files
  build:
    commands:
      - echo Starting build...
      - bash scripts/deploy.sh

cache:
  paths:
    - 'node_modules/**/*'