version: '0.2'

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing system dependencies ..."
      - |
        if command -v yum > /dev/null; then
          yum -y update
          yum -y install gcc
        elif command -v apt-get > /dev/null; then
          apt-get update
          apt-get install -y gcc
        else
          echo "Neither yum nor apt-get found"
          exit 1
        fi
      - echo "Installing Python dependencies ..."
      - pip install --upgrade pip

  pre_build:
    commands:
      - echo "Setting up the environment ..."
      - python -m venv .venv
      - source .venv/bin/activate

  build:
    commands:
      - echo "Installing Python packages ..."
      - pip install -r requirements.txt
      - pip install sagemaker==2.148.0
      - echo "Running the pipeline script ..."
      - bash scripts/run_pipeline.sh

artifacts:
  files:
    - pipelineExecution.json
