version: '0.2'

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing system dependencies ..."
      - |
        if command -v yum > /dev/null; then
          yum -y update
          yum -y install gcc python3-devel libyaml-devel
        elif command -v apt-get > /dev/null; then
          apt-get update
          apt-get install -y gcc python3-dev libyaml-dev
        else
          echo "Neither yum nor apt-get found"
          exit 1
        fi
      - echo "Installing virtualenv ..."
      - pip install virtualenv

  pre_build:
    commands:
      - echo "Setting up the environment ..."
      - virtualenv --copies .venv
      - . .venv/bin/activate

  build:
    commands:
      - echo "Installing Python packages ..."
      - pip install -r ml_pipeline/requirements.txt
      - pip install sagemaker==2.148.0
      - echo "Running the pipeline script ..."
      - bash scripts/run_pipeline.sh

artifacts:
  files:
    - pipelineExecution.json
