version: "0.2"

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Setting up virtual environment..."
      - python -m venv .venv
      - . .venv/bin/activate
      - echo "Upgrading pip, setuptools, and installing dependencies..."
      - pip install --upgrade pip
      - pip install setuptools==57.5.0
      - pip install wheel
      - pip install "Cython<3"
  pre_build:
    commands:
      - echo "Installing Python dependencies..."
      - . .venv/bin/activate
      - pip install boto3==1.29.2  # Updated boto3 to a compatible version
      - pip install "PyYAML==5.4.1" --no-build-isolation
      - pip install sagemaker==2.148.0
      - echo "Dependencies installed successfully"
  build:
    commands:
      - echo "Reading data manifest..."
      - DATA_MANIFEST=$(cat ./dataManifest.json)
      - echo "Starting Pipeline Execution"
      - bash scripts/run_pipeline.sh

artifacts:
  files:
    - 'pipelineExecution.json'