version: "0.2"

env:
  variables:
    pythonversion: 3.10

phases:
  install:
    runtime-versions:
      python: $pythonversion
    commands:
      - echo "Setting up virtual environment..."
      - python -m venv .venv
      - . .venv/bin/activate
      - echo "Upgrading pip, setuptools, and installing dependencies..."
      - pip install --upgrade pip setuptools cython wheel
  pre_build:
    commands:
      - echo "Installing Python dependencies..."
      - . .venv/bin/activate
      - pip install boto3==1.26.118
      - pip install PyYAML==5.4.1 --use-deprecated=legacy-resolver
      - pip install sagemaker==2.148.0
  build:
    commands:
      - echo "Reading data manifest..."
      - DATA_MANIFEST=$(cat ./dataManifest.json)
      - echo "Starting Pipeline Execution"
      - export PYTHONUNBUFFERED=TRUE
      - bash scripts/run_pipeline.sh

artifacts:
  files:
    - 'pipelineExecution.json'