name: CI
on: [push]
jobs:
  ci-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - run: npm install -g typescript
      - run: npm install -g yarn
      - run: pip install virtualenv
      - run: bash scripts/ci.sh
